services:
  api:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - postgres
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/init.sql