POST localhost:8000/suppliers
Content-Type: application/json

{
  "name": "Harry",
  "city": "Wien"
}

###
GET localhost:8000/shelves

###
POST localhost:8000/warehouses
Content-Type: application/json

{"zipCode": 1234, "address": "79999"}

###
POST localhost:8000/shelves
Content-Type: application/json

{"locationCode": "XYZ", "warehouseId": 1}

###
GET localhost:8000/shelves

###
PATCH localhost:8000/suppliers/1
Content-Type: application/json

{"name": "Harold", "city": "Wien"}
